version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: vertex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vertex
      POSTGRES_PASSWORD: vertex_local_dev
      POSTGRES_DB: vertex_main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vertex-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1000", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

